config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  root "stories#index"

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :stories, only: [:index, :create, :destroy]

  get ":user_id", to: "users#show", as: :user

  scope ":user_id", as: :user do
    get "stories", to: "users#stories", as: "stories"
    get "stories_of", to: "users#stories_of", as: "stories_of"
    resources :following, only: [:index, :create, :destroy], as: "followings", controller: "users/followings"
    resources :followers, only: [:index], controller: "users/followers"
    resources :likes, only: [:index, :create, :destroy], controller: "users/likes"
  end
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-fixed-top
  .container.without-sidebar
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li = link_to 'My profile', user_path(current_user)
          li = link_to 'Edit account', edit_user_registration_path
          li = link_to 'Sign out', destroy_user_session_path, method: 'delete'
        - else
          li = link_to 'Sign in', new_user_session_path
          li = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Swindler"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Swindler'}"
    == stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    == javascript_include_tag "application", "data-turbolinks-track" => true
    == csrf_meta_tags
  body
    header
      == render "layouts/navigation"
    main[role="main"]
      .container.without-sidebar
        == render "layouts/messages"
        == yield